# Generated by Django 5.0.6 on 2024-07-08 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
    ]
